#!/usr/bin/env python3
"""Brief 17 §11 — generate the 3 all-channel DPO configs for the
decoy-t1 β-sweep ({0.005, 0.05, 0.5}).

Each output is a near-copy of
``configs/dpo/vhh_dpo_seqonly_filtered_beta0005.yml`` with four edits:

  1. loss_weights: all-channel (rot=1, pos=1, seq=1) instead of seq-only.
  2. dpo.pair_parquet: pairs_decoy_t1_filtered.parquet (the §10
     post-filter pool, which depends on the t=1 PARTIAL-pass pick).
  3. dpo.beta_dpo: 0.005 / 0.05 / 0.5 per variant.
  4. train.max_iters: 5800 (per Brief 17 §11, matches the β-sweep
     horizon; the original 10000 was for seq-only baseline).

The generator is committed alongside the generated configs so the
deltas are reviewable in version control. Re-run after any change to
the base template:

::

    python scripts/dpo/generate_allchannel_decoy_t1_configs.py

Outputs:
  configs/dpo/vhh_dpo_allchannel_decoy_t1_beta0005.yml
  configs/dpo/vhh_dpo_allchannel_decoy_t1_beta05.yml
  configs/dpo/vhh_dpo_allchannel_decoy_t1_beta5.yml
"""
from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
CONFIG_DIR = PROJECT_ROOT / "configs/dpo"
SBATCH_DIR = PROJECT_ROOT / "scripts/dpo/slurm"
BASE_CONFIG = CONFIG_DIR / "vhh_dpo_seqonly_filtered_beta0005.yml"

VARIANTS = [
    ("beta0005", "0.005"),
    ("beta05",   "0.05"),
    ("beta5",    "0.5"),
]

PAIR_PARQUET = (
    "data/aapr/ftseed42_jfix_trainval_K8_20260525/dpo/pairs_decoy_t1_filtered.parquet"
)

SBATCH_TEMPLATE = """#!/bin/bash
# Brief 17 §11 — all-channel DPO on the decoy-t1 pair pool, β={beta_dpo}.
#
# Generated by scripts/dpo/generate_allchannel_decoy_t1_configs.py; do
# not hand-edit (regenerate after touching the template).
#
# Pair pool: pairs_decoy_t1_filtered.parquet (Brief 17 §10 output,
# t=1 winning the §9.2 bathtub sweep with PARTIAL gate pass).
# All channels active: loss_weights {{rot:1, pos:1, seq:1}}.
# max_iters: 5800 (per brief). early_stop_patience: 30 (inherited).
#
# Per-iter cost ≈ 2 s on A100 (4 forwards × ~0.5 s each); 5800 steps
# ≈ 3.2 h compute + val passes ≈ 0.5 h. 4 h walltime is comfortable.

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=18
#SBATCH --mem=120G
#SBATCH --time=04:00:00
#SBATCH --job-name=dpo_ac_decoy_t1_{slug}
#SBATCH --output=logs/slurm/%x_%j.out

set -euo pipefail
module purge
module load 2025 2024 gompi/2024a HMMER/3.4-gompi-2024a
source /projects/0/hpmlprjs/interns/krijn/venvs/DPO/bin/activate
mkdir -p logs/slurm

echo "JobID:    ${{SLURM_JOB_ID:-n/a}}"
echo "Node:     $(hostname)"
echo "GPU:      $(nvidia-smi --query-gpu=name --format=csv,noheader || true)"
echo "Commit:   $(git rev-parse HEAD 2>/dev/null || echo n/a)"
echo "Started:  $(date -Iseconds)"

PAIR_PARQUET=data/aapr/ftseed42_jfix_trainval_K8_20260525/dpo/pairs_decoy_t1_filtered.parquet
if [[ ! -f "$PAIR_PARQUET" ]]; then
    echo "ERROR: $PAIR_PARQUET not found — run §10 filter first." >&2
    exit 1
fi

python scripts/dpo/train_dpo.py \\
    configs/dpo/vhh_dpo_allchannel_decoy_t1_{slug}.yml \\
    --output-dir runs/dpo \\
    --run-name   dpo_allchannel_decoy_t1_{slug} \\
    --num-workers 4 \\
    --wandb-project vhh-dpo \\
    --wandb-run-name dpo_allchannel_decoy_t1_{slug} \\
    --wandb-group   vhh_dpo_brief17_allchannel_t1 \\
    --wandb-mode    online

echo "Finished: $(date -Iseconds)"
"""


def _substitute(text: str, *, beta_dpo: str) -> str:
    """Apply the four Brief 17 §11 edits to the base template."""
    # 1) Loss weights — all-channel.
    # The base config has, exactly:
    #     loss_weights:
    #       rot: 0.0
    #       pos: 0.0
    #       seq: 1.0
    text = text.replace("    rot: 0.0\n    pos: 0.0\n", "    rot: 1.0\n    pos: 1.0\n")

    # 2) Pair parquet — point at the decoy-t1 filtered pool.
    text = text.replace(
        "data/aapr/ftseed42_jfix_trainval_K8_20260525/dpo/pairs_filtered_marginGTp0.0.parquet",
        PAIR_PARQUET,
    )

    # 3) DPO temperature.
    text = text.replace("  beta_dpo: 0.005\n", f"  beta_dpo: {beta_dpo}\n")

    # 4) max_iters — Brief 17 §11 specifies 5800.
    text = text.replace("  max_iters: 10000\n", "  max_iters: 5800\n")

    # 5) Header comment retitle so the file's purpose is visible
    #    without diffing against the base. Replace the first
    #    "VHH Diffusion-DPO ..." line with a brief-17-specific banner.
    text = text.replace(
        "# VHH Diffusion-DPO on the J-anchor-fixed fine-tune (seed42_jfix).\n",
        "# Brief 17 §11 — VHH Diffusion-DPO, ALL-CHANNEL, decoy-t1 pair pool.\n"
        "# Generated by scripts/dpo/generate_allchannel_decoy_t1_configs.py;\n"
        "# do not hand-edit (regenerate after touching the base template).\n",
    )

    # Append a footer comment recording the variant β for grep-ability.
    # Single newline — the file already ends with one.
    text += (
        f"\n"
        f"# ── Variant marker (generator-emitted) ───────────────────────────────\n"
        f"# variant_beta: {beta_dpo}\n"
        f"# campaign:     brief_17_11_allchannel_decoy_t1\n"
    )
    return text


def main() -> int:
    if not BASE_CONFIG.exists():
        print(f"ERROR: base config not found: {BASE_CONFIG}", file=sys.stderr)
        return 2
    base_text = BASE_CONFIG.read_text()

    expected_markers = [
        "    rot: 0.0\n    pos: 0.0\n",
        "data/aapr/ftseed42_jfix_trainval_K8_20260525/dpo/pairs_filtered_marginGTp0.0.parquet",
        "  beta_dpo: 0.005\n",
        "  max_iters: 10000\n",
    ]
    for marker in expected_markers:
        if marker not in base_text:
            print(
                f"ERROR: base config has drifted — expected substring not "
                f"found: {marker!r}. Update the generator's _substitute().",
                file=sys.stderr,
            )
            return 3

    for slug, beta in VARIANTS:
        cfg_path = CONFIG_DIR / f"vhh_dpo_allchannel_decoy_t1_{slug}.yml"
        cfg_path.write_text(_substitute(base_text, beta_dpo=beta))
        print(f"Wrote {cfg_path}  (beta_dpo={beta})")

        sbatch_path = SBATCH_DIR / f"train_dpo_allchannel_decoy_t1_{slug}.sbatch"
        sbatch_path.write_text(SBATCH_TEMPLATE.format(slug=slug, beta_dpo=beta))
        # sbatch files are read by SLURM, but a +x mode bit is harmless
        # and convenient for ad-hoc `bash file.sbatch` smoke tests.
        sbatch_path.chmod(0o755)
        print(f"Wrote {sbatch_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
