"""TNP (Therapeutic Nanobody Profiler) integration layer.

Handles batch execution of TNP via subprocess and parsing of its JSON
output.  TNP performs two functions in one pass:
  1. Folds sequences with NanoBodyBuilder2 (Phase 2)
  2. Computes biophysics metrics: PSH, PPC, PNC, Compactness, CDR lengths

The PDB structures generated by TNP are reused by the Biology and Physics
judges, enforcing the "Fold Once, Judge Many" architecture.
"""

import json
import logging
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


@dataclass
class TNPResult:
    """Parsed TNP output for a single nanobody sequence."""

    psh: float
    ppc: float
    pnc: float
    compactness: float
    cdr_length: int
    cdr3_length: int
    pdb_path: Optional[str] = None
    # TNP traffic-light flags (informational)
    flags: dict[str, str] | None = None


def _write_fasta(sequences: list[dict[str, str]], fasta_path: Path) -> None:
    """Write sequences to a FASTA file for TNP batch input.

    Args:
        sequences: List of dicts with keys "id" and "sequence".
        fasta_path: Output FASTA file path.
    """
    with open(fasta_path, "w") as f:
        for seq in sequences:
            f.write(f">{seq['id']}\n{seq['sequence']}\n")


def _parse_tnp_json(json_path: Path) -> list[dict]:
    """Parse TNP's JSON output file.

    TNP writes either:
      - TNP_Results_SingleSeqEntry_[name].json  (single sequence)
      - TNP_Results_Multientry.json             (batch FASTA)

    Returns:
        List of result dicts, one per sequence.
    """
    with open(json_path) as f:
        data = json.load(f)

    # TNP may return a single dict or a list depending on input mode
    if isinstance(data, dict):
        return [data]
    return data


def _find_tnp_json(output_dir: Path) -> Path | None:
    """Locate the TNP results JSON in the output directory.

    TNP names its output files based on the input mode:
      - Batch FASTA: TNP_Results_Multientry.json
      - Single seq:  TNP_Results_SingleSeqEntry_*.json
    """
    # Prefer the multi-entry file (batch mode)
    multi = output_dir / "TNP_Results_Multientry.json"
    if multi.exists():
        return multi

    # Fallback: look for any single-entry JSON
    singles = list(output_dir.glob("TNP_Results_SingleSeqEntry_*.json"))
    if singles:
        return singles[0]

    return None


def run_tnp_batch(
    sequences: list[dict[str, str]],
    output_dir: Path,
    ncores: int = 1,
) -> dict[str, TNPResult]:
    """Run TNP on a batch of sequences and parse the results.

    This function:
      1. Writes sequences to a temporary FASTA file
      2. Invokes TNP CLI as a subprocess
      3. Parses the JSON output for all 6 metrics
      4. Locates the PDB files generated by NanoBodyBuilder2

    Args:
        sequences: List of dicts with keys "id" (candidate_id) and
                   "sequence" (raw amino acid string).
        output_dir: Directory where TNP will write its output.
        ncores: Number of CPU cores for TNP to use.

    Returns:
        Dict mapping candidate_id to TNPResult.  Sequences that TNP
        failed to process are omitted with a warning.
    """
    if not sequences:
        return {}

    output_dir.mkdir(parents=True, exist_ok=True)

    # Write temporary FASTA
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".fasta", delete=False, dir=output_dir
    ) as tmp:
        fasta_path = Path(tmp.name)
        for seq in sequences:
            tmp.write(f">{seq['id']}\n{seq['sequence']}\n")

    logger.info(
        "Running TNP on %d sequences (ncores=%d, output=%s)",
        len(sequences),
        ncores,
        output_dir,
    )

    # Execute TNP
    cmd = [
        "TNP",
        "--file", str(fasta_path),
        "--output", str(output_dir),
        "--ncores", str(ncores),
        "--name", "pipeline_batch",
        "--web",  # Required for TNP to write JSON result files
    ]

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=True,
        )
        logger.debug("TNP stdout:\n%s", result.stdout)
    except subprocess.CalledProcessError as e:
        logger.error("TNP failed (exit code %d):\n%s", e.returncode, e.stderr)
        raise RuntimeError(f"TNP batch run failed: {e.stderr}") from e
    except FileNotFoundError:
        raise RuntimeError(
            "TNP executable not found. Install TNP from "
            "https://github.com/oxpig/TNP and ensure it is on PATH."
        )
    finally:
        # Clean up temp FASTA
        fasta_path.unlink(missing_ok=True)

    # Parse results
    json_path = _find_tnp_json(output_dir)
    if json_path is None:
        logger.error("No TNP JSON output found in %s", output_dir)
        return {}

    raw_results = _parse_tnp_json(json_path)
    pdb_dir = output_dir / "Final_Models"

    results: dict[str, TNPResult] = {}
    for entry in raw_results:
        name = entry.get("name", "")

        # Locate the PDB file TNP generated
        pdb_path = pdb_dir / f"{name}.pdb"
        resolved_pdb = str(pdb_path) if pdb_path.exists() else None

        try:
            tnp_result = TNPResult(
                psh=float(entry["PSH"]),
                ppc=float(entry["PPC"]),
                pnc=float(entry["PNC"]),
                compactness=float(entry["CDR3 Compactness"]),
                cdr_length=int(entry["Total CDR Length"]),
                cdr3_length=int(entry["CDR3 Length"]),
                pdb_path=resolved_pdb,
                flags=entry.get("Flags"),
            )
            results[name] = tnp_result
        except (KeyError, ValueError, TypeError) as e:
            logger.warning(
                "Failed to parse TNP result for '%s': %s", name, e
            )

    logger.info(
        "TNP completed: %d/%d sequences parsed successfully.",
        len(results),
        len(sequences),
    )

    return results
