"""TNP (Therapeutic Nanobody Profiler) integration layer.

Handles batch execution of TNP via subprocess and parsing of its JSON
output.  TNP performs two functions in one pass:
  1. Folds sequences with NanoBodyBuilder2 (Phase 2)
  2. Computes biophysics metrics: PSH, PPC, PNC, Compactness, CDR lengths

The PDB structures generated by TNP are reused by the Biology and Physics
judges, enforcing the "Fold Once, Judge Many" architecture.
"""

import json
import logging
import subprocess
import tempfile
import threading
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


@dataclass
class TNPResult:
    """Parsed TNP output for a single nanobody sequence."""

    psh: float
    ppc: float
    pnc: float
    compactness: float
    cdr_length: int
    cdr3_length: int
    pdb_path: Optional[str] = None
    # TNP traffic-light flags (informational)
    flags: dict[str, str] | None = None


def _write_fasta(sequences: list[dict[str, str]], fasta_path: Path) -> None:
    """Write sequences to a FASTA file for TNP batch input.

    Args:
        sequences: List of dicts with keys "id" and "sequence".
        fasta_path: Output FASTA file path.
    """
    with open(fasta_path, "w") as f:
        for seq in sequences:
            f.write(f">{seq['id']}\n{seq['sequence']}\n")


def _parse_tnp_json(json_path: Path) -> list[dict]:
    """Parse TNP's JSON output file.

    TNP writes either:
      - TNP_Results_SingleSeqEntry_[name].json  (single sequence)
      - TNP_Results_Multientry.json             (batch FASTA)

    Returns:
        List of result dicts, one per sequence.
    """
    with open(json_path) as f:
        data = json.load(f)

    # TNP output formats:
    #   - list of dicts  → one dict per sequence (older TNP versions)
    #   - dict of dicts  → keyed by sequence name (batch/multi-entry mode)
    #   - single dict    → one sequence result (single-seq mode)
    if isinstance(data, list):
        return data
    if isinstance(data, dict):
        # Check if values are dicts (multi-entry keyed by name)
        first_val = next(iter(data.values()), None)
        if isinstance(first_val, dict):
            return list(data.values())
        # Single sequence result (flat dict with "PSH", "PPC", etc.)
        return [data]
    return []


def _find_tnp_json(output_dir: Path) -> Path | None:
    """Locate the TNP results JSON in the output directory.

    TNP names its output files based on the input mode:
      - Batch FASTA: TNP_Results_Multientry.json
      - Single seq:  TNP_Results_SingleSeqEntry_*.json
    """
    # Prefer the multi-entry file (batch mode)
    multi = output_dir / "TNP_Results_Multientry.json"
    if multi.exists():
        return multi

    # Fallback: look for any single-entry JSON
    singles = list(output_dir.glob("TNP_Results_SingleSeqEntry_*.json"))
    if singles:
        return singles[0]

    return None


def run_tnp_batch(
    sequences: list[dict[str, str]],
    output_dir: Path,
    ncores: int = 1,
) -> dict[str, TNPResult]:
    """Run TNP on a batch of sequences and parse the results.

    This function:
      1. Writes sequences to a temporary FASTA file
      2. Invokes TNP CLI as a subprocess
      3. Parses the JSON output for all 6 metrics
      4. Locates the PDB files generated by NanoBodyBuilder2

    Args:
        sequences: List of dicts with keys "id" (candidate_id) and
                   "sequence" (raw amino acid string).
        output_dir: Directory where TNP will write its output.
        ncores: Number of CPU cores for TNP to use.

    Returns:
        Dict mapping candidate_id to TNPResult.  Sequences that TNP
        failed to process are omitted with a warning.
    """
    if not sequences:
        return {}

    output_dir.mkdir(parents=True, exist_ok=True)

    # Write temporary FASTA
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".fasta", delete=False, dir=output_dir
    ) as tmp:
        fasta_path = Path(tmp.name)
        for seq in sequences:
            tmp.write(f">{seq['id']}\n{seq['sequence']}\n")

    logger.info(
        "Running TNP on %d sequences (ncores=%d, output=%s)",
        len(sequences),
        ncores,
        output_dir,
    )

    # Execute TNP with real-time progress tracking.
    # TNP creates a <name>_TNP.log file per sequence as it completes;
    # we monitor these in a background thread to report progress.
    cmd = [
        "TNP",
        "--file", str(fasta_path),
        "--output", str(output_dir),
        "--ncores", str(ncores),
        "--name", "pipeline_batch",
        "--web",  # Required for TNP to write JSON result files
    ]

    # Remove stale log files from previous runs so the progress monitor
    # starts from zero.
    for old_log in output_dir.glob("*_TNP.log"):
        old_log.unlink(missing_ok=True)

    total_seqs = len(sequences)
    start_time = time.time()
    stop_event = threading.Event()

    def _monitor_progress() -> None:
        """Poll the output directory for per-sequence log files."""
        seen = 0
        while not stop_event.is_set():
            logs = list(output_dir.glob("*_TNP.log"))
            n_done = len(logs)
            if n_done > seen:
                seen = n_done
                elapsed = time.time() - start_time
                per_seq = elapsed / seen
                remaining = per_seq * (total_seqs - seen)
                pct = seen / total_seqs * 100
                bar_len = 30
                filled = int(bar_len * seen // total_seqs)
                bar = "█" * filled + "░" * (bar_len - filled)
                logger.info(
                    "  TNP %s %3.0f%% [%d/%d] | "
                    "%.0fs elapsed | ~%.0fs remaining (%.1fs/seq)",
                    bar, pct, seen, total_seqs,
                    elapsed, remaining, per_seq,
                )
            stop_event.wait(timeout=3.0)

    monitor = threading.Thread(target=_monitor_progress, daemon=True)
    monitor.start()

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=True,
        )
        logger.debug("TNP stdout:\n%s", result.stdout)
    except subprocess.CalledProcessError as e:
        logger.error("TNP failed (exit code %d):\n%s", e.returncode, e.stderr)
        raise RuntimeError(f"TNP batch run failed: {e.stderr}") from e
    except FileNotFoundError:
        raise RuntimeError(
            "TNP executable not found. Install TNP from "
            "https://github.com/oxpig/TNP and ensure it is on PATH."
        )
    finally:
        stop_event.set()
        monitor.join(timeout=5.0)
        fasta_path.unlink(missing_ok=True)

    total_elapsed = time.time() - start_time
    logger.info(
        "  TNP finished in %.0fs (%.1fs/seq avg).",
        total_elapsed, total_elapsed / max(total_seqs, 1),
    )

    # Parse results
    json_path = _find_tnp_json(output_dir)
    if json_path is None:
        logger.error("No TNP JSON output found in %s", output_dir)
        return {}

    raw_results = _parse_tnp_json(json_path)
    pdb_dir = output_dir / "Final_Models"

    results: dict[str, TNPResult] = {}
    for entry in raw_results:
        name = entry.get("name", "")

        # Locate the PDB file TNP generated
        pdb_path = pdb_dir / f"{name}.pdb"
        resolved_pdb = str(pdb_path) if pdb_path.exists() else None

        try:
            tnp_result = TNPResult(
                psh=float(entry["PSH"]),
                ppc=float(entry["PPC"]),
                pnc=float(entry["PNC"]),
                compactness=float(entry["CDR3 Compactness"]),
                cdr_length=int(entry["Total CDR Length"]),
                cdr3_length=int(entry["CDR3 Length"]),
                pdb_path=resolved_pdb,
                flags=entry.get("Flags"),
            )
            results[name] = tnp_result
        except (KeyError, ValueError, TypeError) as e:
            logger.warning(
                "Failed to parse TNP result for '%s': %s", name, e
            )

    logger.info(
        "TNP completed: %d/%d sequences parsed successfully.",
        len(results),
        len(sequences),
    )

    return results
